global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
        labels:
          group: 'monitoring-node'
      - targets: ['10.166.0.5:9100']
        labels:
          group: 'web-node'
  - job_name: 'mariadb'
    static_configs:
      - targets: ['10.166.0.5:9104']
        labels:
          group: 'db-node'
          alias: 'mariadb'
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://public_ip/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
